AWSTemplateFormatVersion: 2010-09-09
Description: Where have you bean csv data bucket, etl lambda, and trigger for lambda 
Resources:

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: where-have-you-bean-lambda #change this
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Code: ./src
      Timeout: 900
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/lambda-execution-role'
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub 'project-networking-VPCSGID'
        SubnetIds:
          - Fn::ImportValue:
              !Sub 'project-networking-PrivateSubnet0ID'

  S3Bucket:
    Type: "AWS::S3::Bucket"
    DependsOn:
      - S3BucketPermission
    Properties:
      BucketName: where-have-you-bean-csv-data-bucket #change this
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaFunction.Arn
      PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True

  S3BucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::where-have-you-bean-csv-data-bucket #change this
